selfrefactor/rambda

.babelrc, package.json
Forgot to include `babel-cli` as dev dependency, hence tests failed.
Possible to release a new npm version ?
=> Include babel cli and es2015 preset

docs/README.md
It was using the example from module function
=> Fix example for multiply function on docs

.babelrc, package.json, yarn.lock
This should make `pathOr` tree-shakeable as its a result of a `curry` call that cannot be tree-shaken easily (as you know), by annotating it with `#__PURE__` (with the help of the babel plugin) we give a hint to uglifyJS that it can be removed if the call's result stay unused
=> Annotate curry calls as #__PURE__

index.d.ts
Added typings for `groupBy`, `indexBy`, `indexOf`, and `lastIndexOf`
=> Added missing typings

README.md
The second example of `take` / `takeLast` shows a string inside an array being trimmed to 2 characters, when it should just show the string not in an array.
=> Update take / takeLast Documentation

index.d.ts
```ts
import { head } from 'rambda';
function fixedHead<T extends Readonly<any> | string>(
list: T,
): T extends string ? string : (T[0] | undefined) {
return list[0];
}
fixedHead('hi'); // it returns string :-)
const test = [[1, 2], [3, 4]];
const test00 = test.map(head).map(x => x); // x is string :'(
const test01 = test.map(fixedHead).map(x => x); // x is number! :-D
```
Thank you for your effort in this lib :smile:
=> fix(typing): fix incorrect inference

package.json, src/assocPath.js, src/assocPath.spec.js
When implementing `assocPath` I assumed that the `_objectIs` helper checks if the type is an object. As it doesn't, nested objects are overwritten rather than augmented. This PR adds a test case that reproduces the problem and fixes it.
=> Fix object check in assocPath

index.d.ts
According to the docs `pathOr` should expect and array of strings or a string, the types dont reflect this, also changed the types for `path` to be a bit cleaner
=> Correct types for path and pathOr

files/ramdaMissing.md
**and** method is implemented and it's in master branch. So, basically this PR is updating the ramdaMissing.md file
=> removed implemented 'and' method from ramdaMissing.md file

README.md, docs/README.md
in the README.md and docs/README.md are shown 2 wrong examples for compose.
removed the usage of both in the examples and REPL
=> fixing wrong documentation example and REPL links for compose

source/curry.js, source/flip.js, source/flip.spec.js
I've removed the arity 5 test because it's not necessary, but I've made sure to cover all codepaths of `flip` in arity 4 test.
As mentionned in the issue, it's necessary to use `curryN` in `curry` to preserve the `Function.length` property.
Closes #464
=> fix@issue #464 make r.flip work for any arity

source/_internals/_isArray.js, source/_internals/isFalsy.js, source/_internals/isTruthy.js, source/applySpec.js, source/assocPath.js, source/change.js, source/clone.js, source/count.js, source/filter.js, source/filterAsync.js, source/flatten.js, source/groupWith.js, source/includes.js, source/isValid.js, source/map.js, source/mapAsync.js, source/partition.js, source/transpose.js, source/type.js
Thoughts about stages you can read here #475 
Not all perf benchs showed. Processing power in some other function will speed up (transpose for ex.).
**Before**
```js
Rambda:
5 045 006 ops/s, ±0.96%     | 95.58% slower
Ramda:
1 697 448 ops/s, ±1.48%     | slowest, 98.51% slower
Lodash:
114 056 063 ops/s, ±2.48%   | fastest
```
**After**
```js
Rambda:
287 421 997 ops/s, ±1.15%   | fastest
Ramda:
1 727 667 ops/s, ±1.27%     | slowest, 99.4% slower
Lodash:
120 056 085 ops/s, ±2.81%   | 58.23% slower
```
**Before**
```js
Rambda:
5 006 674 ops/s, ±0.72%   | fastest
Ramda:
1 310 727 ops/s, ±2.16%   | slowest, 73.82% slower
Lodash.cloneDeep:
1 371 105 ops/s, ±1.97%   | 72.61% slower
```
**After**
```js
Rambda:
144 949 647 ops/s, ±1.19%   | fastest
Ramda:
1 264 141 ops/s, ±1.66%     | 99.13% …
```
=> Accessing isArray method is relatively expensive operation

source/filter.js
1. push is faster than index assignment on modern js engines (tested with latest chromium, firefox, nodejs v14.3.0)
2. Set initial index to zero. No need variable initialization for engine. And look like some perf penalty for negative values.
Tested with 10k values and all pass predicate.
**Before**
```js
Rambda:
14 325 ops/s, ±1.89%   | 8.67% slower
Ramda:
15 685 ops/s, ±1.66%   | fastest
Lodash:
5 824 ops/s, ±2.31%    | slowest, 62.87% slower
```
**After**
```js
Rambda:
16 500 ops/s, ±1.92%   | fastest
Ramda:
15 556 ops/s, ±2.28%   | 5.72% slower
Lodash:
5 799 ops/s, ±2.00%    | slowest, 64.85% slower
```
=> Improve filter performance

source/find.js
Motivation about initial zero index you can find here https://github.com/selfrefactor/rambda/pull/472
Tested with 10k values and false predicate.
**Before**
```js
Rambda:
12 109 ops/s, ±2.35%    | slowest, 93.4% slower
Ramda:
183 486 ops/s, ±1.26%   | fastest
Lodash:
144 319 ops/s, ±0.87%   | 21.35% slower
```
**After**
```js
Rambda:
218 888 ops/s, ±0.79%   | fastest
Ramda:
204 801 ops/s, ±0.92%   | 6.44% slower
Lodash:
141 907 ops/s, ±2.54%   | slowest, 35.17% slower
```
=> Improve find performance

files/index.d.ts, source/of.js, source/of.spec.js, src/of.js
I want to implement juxt and countBy, but I started with something easy, to try to comply with contributing guidelines. Open for suggestions
=> of: test contribution

CHANGELOG.md, README.md, source/path.js, source/path.spec.js, src/path.js
If `null` is result of path, then `undefined` should be returned just like in Ramda.
=> fix: null is not a valid answer

files/index.d.ts, index.d.ts, source/apply-spec.ts, source/apply.js, source/apply.spec.js, source/bind-spec.ts, source/bind.js, source/bind.spec.js, source/converge-spec.ts, source/unapply-spec.ts, source/unapply.js, source/unapply.spec.js
Hey Dejan,
New methods apply, unapply & bind. also a minor bugfix in the converge typescript test as it was referencing ramda not rambda.
Typescript defs are done, methods, tests. I had some trouble coming up with typescript tests for bind, I couldn't get the return type to be what the context is, but this kind of does the same thing proving the context.
No benchmarks as it's not listed in the CONTRIBUTING docs. There is also an error when running `yarn out`. I have installed the rambda-scripts repo in the correct place and can run `yarn new method`. 
```
*(feat@method-apply-unapply-bind)[~/projects/rambda] λ yarn out
yarn run v1.22.11
$ yarn populatedocs && yarn populatereadme && yarn immutable && yarn build
$ cd ../rambda-scripts && yarn populate:docs
$ RAMBDA_SCRIPTS_MODE=populate:docs …
```
=> Feat@method apply unapply bind

docs/index.html
Currently the Rambda documentation site has a title of "Document". This PR should change it to "Rambda Documentation".
=> feat: Improved docs "title" tag

package.json
Now I receive the following error when using with ts-node:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './immutable' is not defined by "exports" in <PATH_TO_PROJECT>/node_modules/rambda/package.json`
=> chore: export immutable.js

.github/README.md, files/index.d.ts, immutable.d.ts, index.d.ts, source/prop-spec.ts
I have a use case on a project, where an object with optional fields has to be passed to a curried `prop` function and type check always fails unless I use some other function.
As I understand, it is not supported by current typing, as there is no way to specify type of the object and `Record` type requires `propToFind` to be defined in the object.
I have also made function argument names more clear.
=> fix: Add support for object type in curried `prop` function

README.md
One of the links changed `Slack int*er*gration` => `Slack int*e*gration`
=> Fixes tiny typo

source/dropLastWhile.js, source/dropWhile.js, source/takeLastWhile.js, source/takeWhile.js
There was some sub-optimal code in these functions. I tried to clean it up while keeping your coding style :smile: 
- don't access iterable more than once per counter
- kill unnecessary boolean flag
- predicate can return falsy, not just false
- don't call predicate on items pointlessly (takeWhile)
=> fix: cleaner dropWhile/dropLastWhile/takeWhile/takeLastwhile

files/index.d.ts, source/endsWith-spec.ts, source/includes-spec.ts, source/startsWith-spec.ts
There might be a better title for this PR.
Starting from TypeScript 4.5 strings can be narrowed: 
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-5.html#template-string-types-as-discriminants
Also see https://github.com/microsoft/TypeScript/pull/46137#issuecomment-932730666
Should I do the same in `@types/ramda` as well?
Also I noticed absence of formatter. Don't you mind enabling something like Prettier?
=> feat: Improve `startsWith`, `includes` and `endsWith` typings for TS 4.5

files/index.d.ts, source/append-spec.ts
The type parameter was declared a second time by mistake, causing the two `T`s to be different type parameters.
**Before:** `R.append(4)` had type `(list: T[]) => T[]`
**After:** `R.append(4)` has type `(list: number[]) => number[]`
=> Fix `R.append`'s curried type

files/index.d.ts, source/anyPass-spec.ts
In the specific case where `R.anyPass()` is combining unary type guards, it can now serve as a unary type guard itself. This allows you to do things like:
```ts
const isJsonLiteral = anyPass([isString, isNumber, isBoolean, isNull]);
```
I would have liked to do `allPass` as well for completeness, but the TypeScript is much more complex, and I'm not sure it comes up as much.
=> `R.anyPass()` can function as a type guard

source/tsconfig.json
Having `strict` off makes it harder for clients of this library to use `strict` themselves. But it appears to turn on without any type issues, so my guess is that there were tricky types in the past which have since been resolved.
I'd understand if you have reservations about turning it on, but I'd highly recommend it, given it turns on cleanly right now.
=> Use `strict: true`

files/index.d.ts, source/append-spec.ts, source/prepend-spec.ts, source/zipObj-spec.ts
Before, `R.prepend(4)` or `R.append(4)` would produce a function which could only be applied to a `number[]`. However, you may well want to append a `4` to an array whose elements can be `number`s or other things, such as a `(string | number)[]`. This commit improves the types to accept such arrays.
You may also have an array of a more specific type (such as `number[]`) and wish to use `R.prepend`/`R.append` to expand the type. Because it's usually a mistake, `append("d")(listOfNumbers)` will cause a type error; however, explicitly calling `append("d")<string | number>(listOfNumbers)` will give you a `(string | number)[]`.
=> `R.prepend`/`R.append` fns accept broader types

files/index.d.ts, source/keys-spec.ts
Surprisingly, `keyof` a type with a string index signature is `string | number`, because:
> JavaScript object keys are always coerced to a string, so `obj[0]` is always the same as `obj["0"]`.
https://www.typescriptlang.org/docs/handbook/2/keyof-types.html
However, `Object.keys` will always return an array of strings, so we can restrict this to types which are also `string` and get the right type.
=> `R.keys` always returns strings

files/index.d.ts, source/partial-spec.ts, source/partial.js, source/partial.spec.js
* **Implementation:** The documentation states that Rambda's partial can either take arguments as an array (like Ramda) or as variadic arguments. However, the implementation didn't actually support the Ramda style. Now it does.
* **Tests:** The tests made it look as if the Ramda style worked. However, this was only because we were concatenating the results with `+`, and `"a" + ["b"] === "a" + "b"`. The tests now truly validate that Ramda style works.
* **Types:** Meanwhile, the types *only* permitted the Ramda style, even though that style didn't work. I've replaced those with a new type which a) supports the variadic style, and b) doesn't rely on a finite set of overrides. There are now only two overrides: one for the variadic style and one for the Ramda style.
=> Fix `R.partial`

files/index.d.ts, source/reduce-spec.ts
The index may be ignored by the reducer, but `reduce()` still provides it. If it's bound to a function parameter, the parameter's value will never be `undefined`; it will always be a `number`.
This mirrors `Array.prototype.map()`, and is already reflected in the first overload of `reduce()`, so I believe this was just a mistake.
=> `reduce()`: Reducer always receives an index

files/index.d.ts, source/composeAsync-spec.ts, source/composeAsync.js, source/mapToObjectAsync-spec.ts, source/pipeAsync-spec.ts, source/pipeAsync.js, source/pipeAsync.spec.js, source/pipedAsync-spec.ts, source/pipedAsync.js, source/pipedAsync.spec.js
This one's a bit beefier than the PRs I've been posting so far. There are a few pieces here that could be accepted or rejected separately, but they all seemed to go together, so I went for the whole thing. Let me know if you'd like me to split this up or resubmit with other changes.
The main goal here was to use `R.pipedAsync`. First, I had a function which returned a constructed `Promise`, which wasn't supported. Then, I noticed that the types for `R.pipedAsync` (as well as `R.composeAsync` and `R.pipeAsync`) weren't really checking types the way their synchronous equivalents were: they were just accepting a type parameter to assert at the end of the chain. While I was in there, I simplified the functions in terms of one another, but they can work just as well in a more explicit form if …
=> Improve composition operators

src/unless.js
This is a type definition from `node_modules/rambda/index.d.ts`
```
export function unless<T, U>(predicate: (x: T) => boolean, whenFalseFn: (x: T) => U, x: T): T | U;
export function unless<T, U>(predicate: (x: T) => boolean, whenFalseFn: (x: T) => U): (x: T) => T | U;
export function unless<T>(predicate: (x: T) => boolean, whenFalseFn: (x: T) => T, x: T): T;
export function unless<T>(predicate: (x: T) => boolean, whenFalseFn: (x: T) => T): (x: T) => T;
```
This is implementation from `node_modules/rambda/src/unless.js`
```
export function unless(predicate, whenFalse){
if (arguments.length === 1){
return _whenFalse => unless(predicate, _whenFalse)
}
return input => predicate(input) ? input : whenFalse(input)
}
```
The problem that this incorrectly works with 3 parameters.
Example:
``` …
```
=> corrected implementation of unless function
